display_name: "capacity-economical-pipeline"
pipeline_root: "gs://oro-smart-capex-state-iac-934643879169-dev/oro-smart-capex-001-dev/notebook_vertex_ai"
package_path: "gs://oro-smart-capex-state-iac-934643879169-dev/oro-smart-capex-001-dev/templates/capacity-economical-pipeline.json"
project_id: "oro-smart-capex-001-dev"
location: "europe-west3"
service_account: "sa-oro-smart-capex-compute-dev@oro-smart-capex-001-dev.iam.gserviceaccount.com"
base_image: "europe-west3-docker.pkg.dev/oro-smart-capex-001-dev/smart-capex-capacity/smartcapex-pipeline/smart-capex-capacity-pipeline-image:0.3.0"
description: "Smart Capex: Capacity Economical Pipeline"

revenues_per_unit_traffic_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_technical_to_economical_revenues_per_site_t"
increase_arpu_due_to_the_upgrade_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_technical_to_economical_increase_of_arpu_by_the_upgrade_t"
processed_capex_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_capex_t"
processed_opex_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_opex_t"

margin_per_site_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_economical_pipeline_margin_per_site_t"
increase_arpu_by_year_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_economical_pipeline_increase_arpu_by_year_t"
cash_flow_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_economical_pipeline_cash_flow_t"
npv_of_the_upgrade_table_id: "oro-smart-capex-001-dev.intermediate_results.capacity_economical_pipeline_npv_of_the_upgrade_t"

NPV:
    WACC: 10
    TIME_TO_COMPUTE_NPV: 6