lte = {'Version': ['Manufacturer', 'Hour_Date', 'Id Data', 'Id VOLTE', 'Id InactivityTime Data',
                   'Id InactivityTime VoLTE', 'nan', 'nan', 'Site', 'AGA001_TDD', 'AGA001_TDD',
                   'AGA001_TDD'],
       'RANDim v7.1.1': ['Huawei', '2023-06-20 10:46:16', '42564', '-1', '42565', '-1', 'nan',
                         'nan', 'Sector', '1', '2', '3'],
       'Unnamed: 2': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Cell',
                      'AGA001_TDD_L1', 'AGA001_TDD_L2', 'AGA001_TDD_L3', ],
       'Unnamed: 3': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Topology inputs', 'MHz',
                      'Frequency Band', 3500, 3500, 3500, ],
       'Unnamed: 4': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'MHz (5,10,15,20)',
                      'Carrier Bandwidth', 20, 20, 20],
       'Unnamed: 5': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '(urban, suburban, rural)',
                      'Environment', 'urban', 'urban', 'urban'],
       'Unnamed: 6': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                      'nan'],
       'Unnamed: 7': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Traffic Inputs', 'Gbytes',
                      'DL traffic forecast Data', 7.360730774, 3.368569417, 2.011678309],
       'Unnamed: 8': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                      'UL traffic forecast Data', 0.364799261, 0.209406612, 0.040295828],
       'Unnamed: 9': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                      'DL traffic forecast VoLTE', 0, 0, 0],
       'Unnamed: 10': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                       'UL traffic forecast VoLTE', 0, 0, 0],
       'Unnamed: 11': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Erlang',
                       'DL E-traffic forecast VOLTE', 'nan', 'nan', 'nan'],
       'Unnamed: 12': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                       'nan'],
       'Unnamed: 13': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Additional Inputs', 's/kBytes',
                       'DL Inactivity time Per kByte', 0.012376412451028194, 0.032812172265826875,
                       0.03112869474201802],
       'Unnamed: 14': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                       'UL Inactivity time Per kByte', 0.24800280502761218, 0.5302079000256209,
                       1.5723890820657662],
       'Unnamed: 15': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                       'DL Inactivity Time Per kByte VoLTE', -1, -1, -1],
       'Unnamed: 16': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                       'UL Inactivity Time Per kByte VoLTE', -1, -1, -1],
       'Unnamed: 17': ['nan', 'nan', 'nan', 'nan', 0, 'nan', 'nan', '%', 'Overhead RRC CA', 0,
                       3.1310076208725492, 11.156543033575616],
       'Unnamed: 18': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '%', 'UECA Config Ratio', 0,
                       3.1310076208725492, 11.156543033575616],
       'Unnamed: 19': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                       'Avg DL data active users', 1.7154, 1.2358, 0.532],
       'Unnamed: 20': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                       'Avg UL data active users', 1.8899, 1.0972, 0.3265],
       'Unnamed: 21': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                       'CAT4 DL CA scheduling', 0, 0, 0],
        'Unnamed: 22': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT6 DL CA scheduling',0,0,0],
       'Unnamed: 23': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                       'CAT10 DL CA scheduling', 0, 0, 0],
       'Unnamed: 24': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                       'CAT12 DL CA scheduling', 0, 0, 0],
       'Unnamed: 25': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                       'CAT18 DL CA scheduling', 0, 0, 0]}

header_lte = {
    'Version': ['Manufacturer', 'Hour_Date', 'Id Data', 'Id VOLTE', 'Id InactivityTime Data',
                'Id InactivityTime VoLTE', 'nan', 'nan', 'Site'],
    'RANDim v7.1.1': ['Huawei', '2023-06-20 10:46:16', '42564', '-1', '42565', '-1', 'nan', 'nan',
                      'Sector'],
    'Unnamed: 2': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Cell'],
    'Unnamed: 3': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Topology inputs', 'MHz',
                   'Frequency Band'],
    'Unnamed: 4': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'MHz (5,10,15,20)',
                   'Carrier Bandwidth'],
    'Unnamed: 5': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '(urban, suburban, rural)',
                   'Environment'],
    'Unnamed: 6': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'],
    'Unnamed: 7': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Traffic Inputs', 'Gbytes',
                   'DL traffic forecast Data'],
    'Unnamed: 8': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                   'UL traffic forecast Data'],
    'Unnamed: 9': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                   'DL traffic forecast VoLTE'],
    'Unnamed: 10': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Gbytes',
                    'UL traffic forecast VoLTE'],
    'Unnamed: 11': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Erlang',
                    'DL E-traffic forecast VOLTE'],
    'Unnamed: 12': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'],
    'Unnamed: 13': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Additional Inputs', 's/kBytes',
                    'DL Inactivity time Per kByte'],
    'Unnamed: 14': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                    'UL Inactivity time Per kByte'],
    'Unnamed: 15': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                    'DL Inactivity Time Per kByte VoLTE'],
    'Unnamed: 16': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 's/kBytes',
                    'UL Inactivity Time Per kByte VoLTE'],
    'Unnamed: 17': ['nan', 'nan', 'nan', 'nan', 0, 'nan', 'nan', '%', 'Overhead RRC CA'],
    'Unnamed: 18': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '%', 'UECA Config Ratio'],
    'Unnamed: 19': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                    'Avg DL data active users'],
    'Unnamed: 20': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
                    'Avg UL data active users'],
    'Unnamed: 21': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT4 DL CA scheduling'],
    'Unnamed: 22': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT6 DL CA scheduling'],
    'Unnamed: 23': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT10 DL CA scheduling'],
    'Unnamed: 24': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT12 DL CA scheduling'],
    'Unnamed: 25': ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'TTI',
                    'CAT18 DL CA scheduling']}

values_columns_lte = ['Site', 'Sector', 'Cell', 'Frequency Band', 'Carrier Bandwidth',
                      'Environment',
                      'nan', 'DL traffic forecast Data', 'UL traffic forecast Data',
                      'DL traffic forecast VoLTE', 'UL traffic forecast VoLTE',
                      'DL E-traffic forecast VOLTE', 'nan', 'DL Inactivity time Per kByte',
                      'UL Inactivity time Per kByte', 'DL Inactivity Time Per kByte VoLTE',
                      'UL Inactivity Time Per kByte VoLTE', 'Overhead RRC CA',
                      'UECA Config Ratio', 'Avg DL data active users', 'Avg UL data active users',
                      'CAT4 DL CA scheduling', 'CAT6 DL CA scheduling', 'CAT10 DL CA scheduling',
                      'CAT12 DL CA scheduling', 'CAT18 DL CA scheduling']
