display_name: "data-preparation-pipeline"
pipeline_root: "gs://oro-smart-capex-state-iac-934643879169-dev/oro-smart-capex-001-dev/notebook_vertex_ai"
package_path: "gs://oro-smart-capex-state-iac-934643879169-dev/oro-smart-capex-001-dev/templates/data-preparation-pipeline.json"
project_id: "oro-smart-capex-001-dev"
location: "europe-west3"
service_account: "sa-oro-smart-capex-compute-dev@oro-smart-capex-001-dev.iam.gserviceaccount.com"
base_image: "europe-west3-docker.pkg.dev/oro-smart-capex-001-dev/smart-capex-capacity/smartcapex-pipeline/smart-capex-capacity-pipeline-image:0.3.0"


# Raw Tables
deployment_history_table_id: "oro-smart-capex-001-dev.smart_capex_raw.v_deployment_history"

oss_3G_table_id: "oro-smart-capex-001-dev.smart_capex_raw.oss_counters_3g_huawei"
oss_3G_history_table_id: "oro-smart-capex-001-dev.smart_capex_raw.oss_counters_3g_huawei_history"

oss_4G_table_id: "oro-smart-capex-001-dev.smart_capex_raw.oss_counters_4g_huawei"
oss_4G_history_table_id: "oro-smart-capex-001-dev.smart_capex_raw.oss_counters_4g_huawei_history"

capex_table_id: "oro-smart-capex-001-dev.smart_capex_raw.capex"
opex_table_id: "oro-smart-capex-001-dev.smart_capex_raw.opex"

# Intermediate Tables
processed_sites_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_sites_region_t"
processed_oss_counter_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_oss_counter_agg_t"
cells_not_to_consider_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_cells_not_to_consider_exp_t"

processed_capex_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_capex_t"
processed_opex_table_id: "oro-smart-capex-001-dev.intermediate_results.data_preparation_opex_t"

OSS_PREPROCESSING:
    NB_WEEKS_RECENT: 48
    NB_WEEKS_UNMOUNTED: 8
    NB_MISSING_WEEKS_ALLOWED: 5
    VARIATION_COEFFICIENT_THRESHOLD: 150
